services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../:/var/www:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - internal

  php-fpm:
    image: php:fpm-alpine
    container_name: php-fpm
    volumes:
      - ../:/var/www:delegated
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - internal

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - internal
    depends_on:
      - php-fpm

  nodejs:
    image: node:lts-alpine
    container_name: nodejs
    volumes:
      - ../:/var/www
    working_dir: /var/www
    entrypoint: ['npm']
    networks:
      - internal

networks:
  internal:
    driver: bridge
