FROM php:7.0-fpm-alpine

ADD .docker/php/www.conf /usr/local/etc/php-fpm.d/www.conf

RUN addgroup -g 1000 webapp && adduser -G webapp -g webapp -s /bin/sh -D webapp

RUN mkdir -p /var/www/html

RUN chown webapp:webapp /var/www/html

WORKDIR /var/www/html

RUN docker-php-ext-install pdo